### PR TITLE
Upgrade to onnxruntime 1.20.0

### PR DESCRIPTION
**Pull request by RJKeevil**
I've done the steps as usual. Please can you run the tests as my environment isn't great for GPU support.  Also I haven't done anything with the now deprecated training stuff, probably that should be removed now in this release also.

### CODE REVIEW

**Comment by yalue** [comment]
Excellent, and thank you!  I will run the tests (at least the ones that I can) and remove training support before tagging a new version in this repo.  My plan will be to make the training functions return an error, and include a note in the README indicating the correct version to use the training API.  Unfortunate that it was deprecated after @riccardopinosio put all the work into adding the bindings.

**Comment by RJKeevil** [comment]
Yes pretty painful they killed it off, and so soon after adding it. Riccardo is working on an alternative in Hugot however!

**Comment by yalue** [comment]
Tested on Windows x86_64, Linux x64_64, and Linux arm64 (all with CPU only).  Currently waiting for my build of onnxruntime 1.20 on aarch64 with CUDA to finish, but I have no reason to expect it not to work.  If it doesn't, I'll just open a new issue I suppose.  Thanks for the help!

**Comment by yalue** [comment]
For what it's worth, I have now tested it on aarch64 using CUDA and TensorRT as well.  It worked without issue:
```
goos: linux
goarch: arm64
pkg: github.com/yalue/onnxruntime_go
BenchmarkOpSingleThreaded
BenchmarkOpSingleThreaded-6   	       1	3395158086 ns/op
BenchmarkOpMultiThreaded
BenchmarkOpMultiThreaded-6    	       1	1019201863 ns/op
BenchmarkCUDASession
BenchmarkCUDASession-6        	       2	 766380430 ns/op
BenchmarkTensorRTSession
BenchmarkTensorRTSession-6    	       4	 260602978 ns/op
```

**Pull request merged**
