### PR TITLE
Allow different types for input and output

### PR DESCRIPTION
**Pull request by Arttii**
Hi,

I am not sure if this makes sense, but I needed to have different types for input and output Tensors. So, I just added another type to the session. It worked so far in my tests.

Also, thanks so much for making this library, it really helped me out!

### CODE REVIEW

**Comment by yalue** [comment]
Hi, and thank you for the change!  The added functionality looks good, but I left a few comments mostly about maintaining API stability.  Changing the `Session` struct to have two type parameters sounds good to me, but I'd rather leave the current single-type versions of the Session "constructor" functions in place.

**Comment by yalue** [comment]
Yes, exactly!  Preferably use T1 and T2 for the type names ([as in the proposal where multiple parameters are used](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md)).  You can also change the definition of `NewSession[T](...)` to call `NewSessionWithOutputType[T1, T2](...)` to reduce repeated code.  Something like this, I'd expect:

```go
func NewSession[T TensorData](onnxFilePath string, inputNames,
	outputNames []string, inputs, outputs []*Tensor[T]) (*Session[T], error) {
	return NewSessionWithOutputType[T, T](onnxFilePath, inputNames, outputNames, inputs, outputs)
}
```

**Comment by yujong-lee** [comment]
I had same problem and using [forked version](https://github.com/yujong-lee/onnxruntime_go/commit/4ca77bf055795d6ef3abaf82fecb7174bf6d7e39) and came across here.

@yalue  Can we merge this PR?

**Comment by yalue** [comment]
Hi, sorry for the lack of activity on this one, and I'm partially to blame here.  I'd like to solve this in a way that maintains API stability, perhaps by creating a new type of `Session` struct with a different name so existing users wouldn't need to update their code to change the type parameters.  As that fork shows, the session doesn't even need type parameters at all, so if I make a change like this I'd rather go that route instead of the one I thought would work for this change.

I guess the point is that I'm still thinking about how to best handle this, and I'm sorry for not merging it yet.

**Comment by yalue** [comment]
Hello again, sorry it took so long to address this, but different input and output types should now be possible using the `DynamicSession` type added in PR #9.

**Pull request closed without merging**
