### PR TITLE
Upgrade to onnxruntime 1.19.0

### PR DESCRIPTION
**Pull request by RJKeevil**
Changes made as per your previous instructions, haven't tested yet but submitting PR now in case you were also planning to perform this upgrade.  Thanks!

### CODE REVIEW

**Comment by RJKeevil** [comment]
Ok all CPU tests pass successfully, still have issues with DirectML and CUDA on windows, perhaps you can verify them for me?

**Comment by yalue** [comment]
Looks good to me at a glance; I'll make sure the CUDA and TensorRT tests pass as well.  Sorry I haven't done it yet; I should get to it later today!

**Comment by yalue** [comment]
Quick update: I am still trying to test this, but updating CUDA is a pain to do without breaking other stuff on my system.  At least I can confirm that the CPU execution provider works on my system.  I apologize for the delay here, and if I take too long I may just merge this and deal with issues later.  (After all, CPU execution is fine, and chances were small that any changes introduced here are the fault of the Go wrapper.)

I may also update the README indicating the tagged version that's required for people wanting to stay on CUDA 11.8.  It's kind of a big change, since all of the previous versions of this library have worked with 11.8.  Someone blindly updating their go.mod may end up needing to update their CUDA version as well.

**Comment by RJKeevil** [comment]
Hi @yalue , I tested CUDA from within a Docker container, but it was segfaulting on setting CUDA options.  It could be environmental still, but just letting you know it might be risky to just merge this without testing CUDA first.

**Comment by RJKeevil** [comment]
OK it was my environment, I tried this on a different laptop and Cuda ran sucessfully.  I think we are good.

**Comment by yalue** [comment]
Great to hear, and I expect to merge it soon.  I do want to make sure I can get it working myself, first, though I haven't had a chance to try again yet.  I expect this to cause an annoyance for plenty of others, but CUDA 12 has been out for over a year and a half, best to get it over with :)  I'll need to prioritize adding a note to the README for CUDA 11 users, mentioning the specific tag, onnxruntime version, and `onnxruntime_go` version needed if they want to stay on 11.8.

**Comment by RJKeevil** [comment]
I can also have a stab at updating the readme if you like @yalue ?

**Comment by yalue** [comment]
Sorry about the slow response; I've been traveling with sporadic internet access at best.  Though, yes, I'd appreciate it if you updated the README as well; just toss it in with this PR and I'll accept it when I next have internet access.

**Comment by RJKeevil** [comment]
No problem, i've pushed an attempt at the readme, hope its what you had in mind.  Happy travelling!

**Comment by yalue** [comment]
Looks good, thanks.

**Comment by RJKeevil** [comment]
Great stuff, do you plan also to tag this as a release?

**Comment by yalue** [comment]
Oops, I just forgot as usual.  Thanks for the reminder, it's now in `v1.12.0`.

**Pull request merged**
